index:
    pattern: /
    defaults: { _controller: HypnosMainBundle:Default:index,page:home }

HypnosMainBundle:
    resource: "@HypnosMainBundle/Resources/config/routing.yml"
    prefix: /

HypnosSupportBundle:
    resource: "@HypnosSupportBundle/Resources/config/routing.yml"
    prefix: /

