parameters:
#    hypnos_main.example.class: Hypnos\MainBundle\Example

services:
#    hypnos_main.example:
#        class: %hypnos_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
